CC = gcc

all:  crack_des-hw1-1628927 crack_des_single-hw1-1628927

crack_des-hw1-1628927: crack_des-hw1-1628927.c
	$(CC) crack_des-hw1-1628927.c -o crack_des-hw1-1628927 -lpthread 

crack_des_single-hw1-1628927: crack_des_single-hw1-1628927.c
	$(CC) crack_des_single-hw1-1628927.c -o crack_des_single-hw1-1628927

clean:
	rm -f crack_des-hw1-1628927 crack_des_single-hw1-1628927

.PHONY: clean
